"""Build the takedown pack: the artifact an analyst actually files.

ZIP containing findings.csv, evidence.json, report.md (one section per confirmed number
with replayable SerpApi links and the report form for each surface) and a complaint
template for cybercrime.gov.in. Only findings the analyst kept in the pack are included.
"""

from __future__ import annotations

import csv
import io
import json
import zipfile
from datetime import UTC, datetime

from helpline_watch.models import Brand, Finding, Surface, Sweep

GOOGLE_BUSINESS_REDRESSAL = "https://support.google.com/business/contact/business_redressal_form"
GOOGLE_ADS_REPORT = "https://support.google.com/google-ads/troubleshooter/4578507"
GOOGLE_SEARCH_REPORT = "https://www.google.com/webmasters/tools/legal-removal-request?complaint_type=rtbf"
CYBERCRIME_PORTAL = "https://cybercrime.gov.in"
CYBERCRIME_HELPLINE = "1930"


def maps_place_url(place_id: str | None) -> str | None:
    return f"https://www.google.com/maps/place/?q=place_id:{place_id}" if place_id else None


def _surface_action(surface: Surface, finding: Finding) -> str:
    if surface == Surface.MAPS or surface == Surface.SEARCH_LOCAL:
        places = [o.listing.place_id for o in finding.observations if o.listing and o.listing.place_id]
        link = maps_place_url(places[0]) if places else None
        return f"Maps listing: open {link or 'the listing'} → “Suggest an edit” → “Remove this place”, and file the Business Redressal form: {GOOGLE_BUSINESS_REDRESSAL}"
    if surface == Surface.SEARCH_ADS or surface == Surface.ADS_TRANSPARENCY:
        return f"Search ad: report the ad via {GOOGLE_ADS_REPORT} (policy: misrepresentation / impersonation)."
    return f"Web page: request removal from the site owner; for legal/impersonation removals use {GOOGLE_SEARCH_REPORT}."


def _report_md(sweep: Sweep, brand: Brand, findings: list[Finding]) -> str:
    when = (sweep.finished_at or sweep.started_at).strftime("%d %b %Y %H:%M UTC")
    lines = [
        f"# Takedown pack — {brand.name}",
        "",
        f"Generated by Helpline Watch from sweep `{sweep.id}` ({when}), mode: {sweep.mode}, cities: {', '.join(sweep.city_ids)}.",
        f"Fixture kinds in this sweep: {json.dumps(sweep.fixture_kinds)}. Synthetic fixtures are demo data, not evidence.",
        "",
        f"Official numbers on file: {', '.join(brand.official_numbers) or 'none'}",
        "",
        f"## {len(findings)} numbers to take down",
        "",
    ]
    for i, f in enumerate(findings, 1):
        lines += [f"### {i}. {f.display}  ·  verdict: {f.verdict.value}  ·  score {f.score}", ""]
        for s in f.signals:
            lines.append(f"- **{s.code}** (+{s.weight}): {s.detail}")
        if f.other_brands:
            lines.append(f"- Also posing as: {', '.join(f.other_brands)}")
        lines += ["", "Evidence:", ""]
        for o in f.observations:
            where = f"{o.surface.value} · {o.city_id or 'national'}"
            src = o.source_link or (o.listing.title if o.listing else "") or ""
            archive = f" · replay: {o.provenance.archive_link}" if o.provenance.archive_link else " · (synthetic fixture, no archive)" if o.provenance.fixture_kind == "synthetic" else ""
            lines.append(f"- {where} · {src}{archive}")
            lines.append(f"  > {o.context}")
        lines += ["", "Actions:", ""]
        for surface in f.surfaces:
            lines.append(f"- {_surface_action(surface, f)}")
        lines += [f"- Report to the national cybercrime portal {CYBERCRIME_PORTAL} (helpline {CYBERCRIME_HELPLINE}); template in complaint_template.txt.", ""]
    return "\n".join(lines)


def _complaint_template(brand: Brand, findings: list[Finding]) -> str:
    numbers = "\n".join(f"  - {f.display} ({', '.join(s.value for s in f.surfaces)}; cities: {', '.join(f.city_ids) or 'n/a'})" for f in findings)
    return f"""To: National Cyber Crime Reporting Portal (cybercrime.gov.in) / Cyber Crime Cell
Subject: Fake customer-care numbers impersonating {brand.name} found on Google surfaces

Sir/Madam,

During a monitoring sweep on {datetime.now(UTC).strftime('%d %B %Y')}, the following phone numbers were found presented to the public as {brand.name} customer-care / helpline numbers on Google Search, Google Maps listings and/or Google ads. None of them is an official {brand.name} number. Official numbers are: {', '.join(brand.official_numbers) or 'listed on the official website'}.

Numbers:
{numbers}

Evidence (search archive links and screenshots) is attached as evidence.json and report.md. We request that the numbers be investigated and blocked, and that the listings and ads be removed.

Contact person: ____________________
Organisation: {brand.name}
Phone / email: ____________________
"""


def build_pack(sweep: Sweep, brand: Brand) -> bytes:
    findings = [f for f in sweep.findings if f.in_pack]
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        csv_buf = io.StringIO()
        w = csv.writer(csv_buf)
        w.writerow(["number", "verdict", "score", "signals", "surfaces", "cities", "other_brands", "first_source", "archive_link"])
        for f in findings:
            first = f.observations[0] if f.observations else None
            w.writerow([f.display, f.verdict.value, f.score, "; ".join(s.code for s in f.signals), "; ".join(s.value for s in f.surfaces),
                        "; ".join(f.city_ids), "; ".join(f.other_brands), (first.source_link or (first.listing.title if first and first.listing else "")) if first else "",
                        (first.provenance.archive_link or "") if first else ""])
        z.writestr("findings.csv", csv_buf.getvalue())
        z.writestr("evidence.json", json.dumps([f.model_dump(mode="json") for f in findings], indent=1, ensure_ascii=False))
        z.writestr("report.md", _report_md(sweep, brand, findings))
        z.writestr("complaint_template.txt", _complaint_template(brand, findings))
    return buf.getvalue()
